version: 2
updates:

  # Badger backend dependencies
  - package-ecosystem: "gomod"
    directory: "/badger"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:30"
    open-pull-requests-limit: 3
    commit-message:
      prefix: "deps(badger)"
      include: "scope"
    labels:
      - "dependencies"
      - "go"
      - "backend"
      - "badger"
    groups:
      badger-dependencies:
        patterns:
          - "*"

  # Consul backend dependencies  
  - package-ecosystem: "gomod"
    directory: "/consul"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "10:00"
    open-pull-requests-limit: 3
    commit-message:
      prefix: "deps(consul)"
      include: "scope"
    labels:
      - "dependencies"
      - "go"
      - "backend"
      - "consul"
    groups:
      consul-dependencies:
        patterns:
          - "*"

  # DynamoDB backend dependencies
  - package-ecosystem: "gomod"
    directory: "/dynamodb"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "10:30"
    open-pull-requests-limit: 3
    commit-message:
      prefix: "deps(dynamodb)"
      include: "scope"
    labels:
      - "dependencies"
      - "go"
      - "backend"
      - "dynamodb"
    groups:
      dynamodb-dependencies:
        patterns:
          - "*"

  # etcd backend dependencies
  - package-ecosystem: "gomod"
    directory: "/etcd"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "11:00"
    open-pull-requests-limit: 3
    commit-message:
      prefix: "deps(etcd)"
      include: "scope"
    labels:
      - "dependencies"
      - "go"
      - "backend"
      - "etcd"
    groups:
      etcd-dependencies:
        patterns:
          - "*"

  # Local/BoltDB backend dependencies
  - package-ecosystem: "gomod"
    directory: "/local"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "11:30"
    open-pull-requests-limit: 3
    commit-message:
      prefix: "deps(local)"
      include: "scope"
    labels:
      - "dependencies"
      - "go"
      - "backend"
      - "local"
    groups:
      local-dependencies:
        patterns:
          - "*"

  # Memcached backend dependencies
  - package-ecosystem: "gomod"
    directory: "/memcached"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "12:00"
    open-pull-requests-limit: 3
    commit-message:
      prefix: "deps(memcached)"
      include: "scope"
    labels:
      - "dependencies"
      - "go"
      - "backend"
      - "memcached"
    groups:
      memcached-dependencies:
        patterns:
          - "*"

  # MongoDB backend dependencies
  - package-ecosystem: "gomod"
    directory: "/mongodb"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "12:15"
    open-pull-requests-limit: 3
    commit-message:
      prefix: "deps(mongodb)"
      include: "scope"
    labels:
      - "dependencies"
      - "go"
      - "backend"
      - "mongodb"
    groups:
      mongodb-dependencies:
        patterns:
          - "*"

  # Redis backend dependencies
  - package-ecosystem: "gomod"
    directory: "/redis"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "12:30"
    open-pull-requests-limit: 3
    commit-message:
      prefix: "deps(redis)"
      include: "scope"
    labels:
      - "dependencies"
      - "go"
      - "backend"
      - "redis"
    groups:
      redis-dependencies:
        patterns:
          - "*"

  # MySQL backend dependencies
  - package-ecosystem: "gomod"
    directory: "/mysql"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "13:00"
    open-pull-requests-limit: 3
    commit-message:
      prefix: "deps(mysql)"
      include: "scope"
    labels:
      - "dependencies"
      - "go"
      - "backend"
      - "mysql"
    groups:
      mysql-dependencies:
        patterns:
          - "*"

  # PostgreSQL backend dependencies
  - package-ecosystem: "gomod"
    directory: "/postgresql"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "13:30"
    open-pull-requests-limit: 3
    commit-message:
      prefix: "deps(postgresql)"
      include: "scope"
    labels:
      - "dependencies"
      - "go"
      - "backend"
      - "postgresql"
    groups:
      postgresql-dependencies:
        patterns:
          - "*"